default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  reconnect: true
  encoding: unicode

development:
  <<: *default
  database: mind-api-development
  host: localhost

test:
  <<: *default
  database: mind-api-test

production:
  <<: *default
  database: mind-api-production